version: '3'
services:
 mysql:
  image: mysql
  container_name: mysql
  env_file: variables.env
  networks:
   - back
  volumes:
   - ./mysql_vol:/var/lib/mysql

 nginx:
  image: nginx
  depends_on:
   - ghost
  volumes:
   - ./default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  networks:
   - front

 ghost:  
  image: ghost
  volumes:
   - ./config.js:/var/lib/ghost/config.js
  container_name: ghost
  depends_on:
    - mysql
  networks:
   - front
   - back

networks:
 front:
 back:
